apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


secretGenerator:
- name: mysql-pass
  literals:
  - password=passw0rd123
resources:
  - efs-provisioner.yml
  - rbac.yml
  - efs-sc.yml
  - efsmysql.yml
  - efswp.yml